Ensure LaTeX renderer uses valid \verb delimiter
miyuchina/mistletoe pull request #150
Opened 2022-07-07 18:09 UTC by joel-coffman

The LaTeX renderer uses `\verb` for inline code, but the delimiter is
always a vertical bar, which produces incorrect output when the inline
code also contains a vertical bar (e.g., `example | pipe`).

Rather than using a single static character (i.e., a vertical bar),
this change modifies render_inline_code to search for a non-letter
delimiter that does not appear in the inline code. If no such
delimiter can be found, a RuntimeError is raised to avoid incorrect
output.

Note that the list of possible delimiters is not exhaustive. For
example, numbers (0, 1, 2, etc.) are all valid delimiters for \verb
but are omitted from the search.

Fixes #149

2022-07-09 19:24 UTC, pbodnar commented
@joel-coffman, thanks for this PR, I like it. :)

Maybe just 1 question to the delimiters set - currently it is:

    |+=!@#$^&`~-_:

I have read that the only character which cannot be used is `*`. So I wonder if you don't want to add some other characters like `%`, `;`, `/` or even `?`, "just for completeness". I also wonder about the _order_ of the possible delimiters - do we set the order more or less randomly, or is it possible / does it pay off to do something like "(estimating) frequency analysis" for choosing "the best order"? 

I guess you answer me that it probably wouldn't make any big difference, but I'm still asking for the case you would like to do some amendments after all.

2022-07-09 21:55 UTC, joel-coffman commented
Good questions! Let me try my best to respond.

> Maybe just 2 questions to the delimiters set - currently it is:
> 
> ```
> |+=!@#$^&`~-_:
> ```
> 
> I have read that the only character which cannot be used is `*`. So I wonder if you don't want to add some other characters like `%`, `;`, `/` or even `?`, "just for completeness".

I wasn't sure where to find an exhaustive list of the possible delimiters. We may overlook at least one no matter how hard we try. :-/

Maybe [`string.punctuation`](https://docs.python.org/3/library/string.html#string.punctuation) (excluding, of course, `*`) would be a better choice than trying to enumerate them all here? Of course, even that set omits digits (0, 1, ..., 9) so I think it really comes down to 1) how paranoid we should be trying to find a valid delimiter and 2) the potential for confusion when reading the output (e.g., `\verb(a | b(` is valid but [just looks wrong](https://tex.stackexchange.com/a/387691)). Given that we're trying to handle arbitrary code that can contain any character, I don't think a general solution is possible. With that said, I think `string.punctuation` is better than the current implementation, and I'm happy to update this merge request if you concur.

> I also wonder about the _order_ of the possible delimiters - do we set the order more or less randomly, or is it possible / does it pay off to do something like "(estimating) frequency analysis" for choosing "the best order"?

I thought it would be good to have the vertical bar (`|`) first to preserve the current behavior as long as the inline code doesn't contain a vertical bar itself. That is, a document created before this change is merged would be the same as a document created after this change is merged *unless* the inline code happens to contain a vertical bar.

Considering the programming languages that I know, I cannot think of a single ordering of the possible delimiters that works well for all of them. If you have ideas, then I'm certainly open to them.

2022-07-15 15:51 UTC, joel-coffman commented
> @joel-coffman, sorry for the delay, I'm back again...
> 
> Firstly, thank you for your analysis. :)
> 
> Regarding the _characters set_, [`string.punctuation`](https://docs.python.org/3/library/string.html#string.punctuation) does seem like a good source of inspiration, although I would also vote for omitting any kind of brackets from the list and to keep an own constant for this.
> 
> Regarding _characters order_, I agree that `|` needs to go first and I don't have any special preference over the rest, except maybe just that:
> 
> * `!` could go as the 2nd one (as it is quite similar to `|`)
> * either order the rest of the characters like they do it in `string.punctuation`, or order them according to their location on the standard English keyboard. I would probably leave it up to you to decide. ;)

Addressed by 5d9b154. The renderer now has a constant for the delimiters, which can be overridden to omit braces, brackets, etc. In short, everything possible is tried, and if the user doesn't like the exhaustive set of possible delimiters, then they can restrict the set however they please.

2022-07-16 07:03 UTC, pbodnar requested changes
@joel-coffman, thanks a lot. I haven't expected you will choose the harder way, but I think it is basically just fine, so I would accept it. Although can you please have a look at my small improvements suggestions firstly? :)

2022-07-18 11:50 UTC, joel-coffman commented
> @joel-coffman, thanks a lot. I haven't expected you will choose the harder way, but I think it is basically just fine, so I would accept it. Although can you please have a look at my small improvements suggestions firstly? :)

Great suggestions, @pbodnar! All are addressed by b37787f.

2022-07-18 11:51 UTC, joel-coffman commented on mistletoe/latex_renderer.py
> +        # (customizable) delimiters for inline code
Resolved by b37787f

2022-07-18 11:51 UTC, joel-coffman commented on mistletoe/latex_renderer.py
> +        for delimiter in list('*'):
Resolved by b37787f

2022-07-18 11:51 UTC, joel-coffman commented on mistletoe/latex_renderer.py
> +        for i, delimiter in enumerate(['|', '!', '"', '\'', '=', '+']):
Resolved by b37787f

2022-07-20 06:32 UTC, pbodnar commented
Addendum: It also helps to have the issue number at the end of the 1st commit message line, like this: `Ensure LaTeX renderer uses valid \verb delimiter (#149)`.

2022-07-23 16:57 UTC, joel-coffman commented
Good catch on the unused import!

I think that these issues / requests have been addressed, but let me know if I've overlooked anything.

2022-07-24 08:40 UTC, pbodnar commented
@joel-coffman, thank you. Strangely enough, the `Compare` button here doesn't show any differences, yet the `import string` seems to be correctly removed - so regarding the content, I think it is perfect now. :)

Only regarding the commit messages' summaries, I hope I don't bother you too much about this ;), I would prefer something like this (to sum up my previous suggestions):

* `Ensure LaTeX renderer uses valid \verb delimiter (#149)`
* `Try all possible delimiters for LaTeX \verb (#149)`

2022-07-25 11:54 UTC, joel-coffman commented
No problem, @pbodnar! I've updated the second commit message to include the issue number in the summary. Please let me know if you'd like anything else related to this change.

2022-07-25 18:10 UTC, pbodnar commented
@joel-coffman, I was hoping for also including the word `LaTeX`. :)

2022-07-25 19:06 UTC, joel-coffman commented
Ah, sorry! I missed that when I read your comment. Anyway, the latest rebase includes "LaTeX" in the second commit message summary.

2022-07-26 06:59 UTC, pbodnar approved these changes

2022-07-26 06:59 UTC, merged

2022-07-26 07:00 UTC, pbodnar commented
All OK now, thank you! :)