fix: Correct typo in logic for filtering children by class in traverse()
miyuchina/mistletoe pull request #157
Opened 2022-08-28 13:18 UTC by asb

The `traverse()` utility function was previously written to filter
children by class using `issubclass(child, klass):`. But the first
argument to `issubclass()` must be a class so this will always raise an
exception when trying to use the functionality. This patch corrects the
call to `isinstance(child, klass)` and adds a test.

2022-08-28 20:44 UTC, pbodnar requested changes
@asb, thank you for the fix. I guess it was a mistake to accept the previous PR without a more complete set of tests.

If you don't mind, I have just slightly changed the PR title - can you please do the same with your commit message, while amending the commit with my little suggestion from the code review? :)

2022-08-28 20:44 UTC, pbodnar commented on test/test_traverse.py
> +    def test_b(self):
A small suggestion:

```suggestion
    def test_with_class_filter(self):
```

Also, to have more meaningful testing methods names, we could also rename the first testing method, e.g. to `test_with_included_source`?

2022-08-28 21:18 UTC, asb commented
@pbodnar: thanks for such a rapid review, I've made the suggested changes.

It's an unfortunate bug, but the traverse utility does seem pretty handy to have in the codebase. It's nice to have a helper to make it easier to do information extraction or even light modifications at the AST level, as an alternative/companion to customising the renderer.

2022-08-29 18:13 UTC, pbodnar approved these changes

2022-08-29 18:15 UTC, merged

2022-08-29 18:15 UTC, pbodnar commented
@asb, thanks for the quick fix. :)

2022-08-29 18:24 UTC, asb commented
I'm now wondering what the behaviour should be when specifying a class to filter on and also setting `include_source=True`. As it is, the 'source' node will be yielded even if it doesn't match the filter. Perhaps it doesn't matter much either way, but this seems a little surprising to me. It also doesn't seem too important one way or another though.

Given filtering by class didn't work previously, there's an opportunity to tweak this without breaking anyone's code.

2022-09-01 19:23 UTC, pbodnar commented
@asb, good point. I can imagine that most people would expect, like you, that filtering by class will always win over `include_source=True`. In that case, to follow the principle of least surprise, we should probably change the current behavior. Are you willing to do the change yourself (change impl. + doc + unit test)?

2022-09-02 07:54 UTC, asb commented
Sure thing - see https://github.com/miyuchina/mistletoe/pull/158