Make tables interrupt paragraphs (#166)
miyuchina/mistletoe pull request #187
Opened 2023-06-25 08:19 UTC by anderskaplan

This PR introduces a more modular way to detect when a block token interrupts a paragraph. It also makes `Table` tokens interrupt paragraphs, using the new mechanism.

In addition to the "obvious" use in `Paragraph.read()`, checks for paragraph interruptions are also done in `Quote.read()` and `ListItem.read()` to determine whether a line is a lazy continuation line or not.

Using the new mechanism to check for continuation lines in `Quote` and `ListItem` does change the parsing behavior, and I believe it's for the better. The old implementation of these checks did not include `HTMLBlock`, for example. There are no test cases in the CommonMark test suite to prove it, but I believe the new implementation is closer to the definition of "[Paragraph continuation text](https://spec.commonmark.org/0.30/#paragraph-continuation-text)" in the CommonMark spec.

Up for discussion: as it says in the issue report (#166), making `Table` interrupt paragraphs is a change of behavior, and maybe it should be a setting. If so, I'd propose to add the setting to the `Table` class, rather than to make it a renderer parameter, because this is a parsing option and it has nothing to do with the rendering.

2023-07-29 07:52 UTC, pbodnar commented
@anderskaplan, while rebasing, I think you would also want to restructure the commits a bit - namely the very last commit currently (6ed847e07fc9203f2b1f872dcbfba51fb0db4b16) content doesn't seem to quite match what is in the commit message?

2023-07-30 14:34 UTC, anderskaplan commented
> @anderskaplan, while rebasing, I think you would also want to restructure the commits a bit - namely the very last commit currently ([6ed847e](https://github.com/miyuchina/mistletoe/commit/6ed847e07fc9203f2b1f872dcbfba51fb0db4b16)) content doesn't seem to quite match what is in the commit message?

I've clarified the commit message a little, but overall I think it was correct -- it's the override of the `check_interrupts_paragraph` method that does the trick, once the groundwork has been done.

2023-08-06 11:34 UTC, pbodnar requested changes
Thank you, LGTM! :)

Maybe just what about squashing the 2 commits which follow after e2829a43575c84a750? Or changing their commit message a bit. So that the relation among them (doing de-facto the same for Paragraphs, but also for Quotes and List items) is more visible?

2023-08-06 11:40 UTC, pbodnar commented
> Up for discussion: as it says in the issue report (#166), making `Table` interrupt paragraphs is a change of behavior, and maybe it should be a setting. If so, I'd propose to add the setting to the `Table` class, rather than to make it a renderer parameter, because this is a parsing option and it has nothing to do with the rendering.

Yes, I would make this a _parsing_ option, i.e. to keep it separate from the options we pass to the various renderers now. I haven't thought about the exact form yet, so if you've already got an idea, that would be great... Maybe introducing a global "parsing options" variable would be the only way for now, without the necessity to do a major refactoring?

2023-08-06 16:16 UTC, anderskaplan commented
> Maybe just what about squashing the 2 commits which follow after [e2829a4](https://github.com/miyuchina/mistletoe/commit/e2829a43575c84a750af4b16fdf38c61ccafd7a4)? Or changing their commit message a bit. So that the relation among them (doing de-facto the same for Paragraphs, but also for Quotes and List items) is more visible?

Sure, I think even the 4 commits after [e2829a4] could be squashed into one.

2023-08-06 16:17 UTC, anderskaplan commented
> Yes, I would make this a _parsing_ option, i.e. to keep it separate from the options we pass to the various renderers now. I haven't thought about the exact form yet, so if you've already got an idea, that would be great... Maybe introducing a global "parsing options" variable would be the only way for now, without the necessity to do a major refactoring?

I'll think about it and come up with a suggestion :)

2023-08-13 09:40 UTC, pbodnar approved these changes

2023-08-13 09:51 UTC, pbodnar commented
@anderskaplan, thanks a lot, good job. 👍 

So we newly allow tables to interrupt paragraphs by default - I will address this in the release notes, mentioning the option `block_token.Table.interrupt_paragraph` there.

2023-08-13 09:51 UTC, merged